FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y nginx libnginx-mod-http-fancyindex && \
    apt-get autoclean

ADD nginx.conf /etc/nginx/nginx.conf
ADD footer.shtml /www/
ADD style.css /www/css/
ADD index.html /www/

ADD cert.* /opt/certs/

CMD ["nginx", "-g", "daemon off;"]