FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y nginx libnginx-mod-http-fancyindex && \
    apt-get autoclean

ADD nginx.conf /etc/nginx/nginx.conf
ADD index.html /www/

CMD ["nginx", "-g", "daemon off;"]